#ArithmeticOperatorsEx1.py
a=int(input("Enter Value of a:"))
b=int(input("Enter Value of b:"))
print("*"*50)
print("Results of Arithmetic Operators")
print("*"*50)
print("\tsum({},{})={}".format(a,b,a+b))
print("\tsub({},{})={}".format(a,b,a-b))
print("\tmul({},{})={}".format(a,b,a*b))
print("\tdiv({},{})={}".format(a,b,a/b))
print("\tfllor_div({},{})={}".format(a,b,a//b))
print("\tmod({},{})={}".format(a,b,a%b))
print("\tpow({},{})={}".format(a,b,a**b))
print("*"*50)